### ISSUE TITLE
Помоги пж

### ISSUE THREAD

**Issue by Tr-T59** [Tr-T59/Study#2]
https://github.com/Tr-T59/Study/tree/main/UML/11062022 Я не шарю в диаграммах классов

**Comment by DrDeLaBill** [comment]
Можно подумать я шарю

**Comment by DrDeLaBill** [comment]
В целом, могу посмотреть попозже, как это закодить

**Comment by Tr-T59** [comment]
остынь военный, кодить не надо


ср, 29 июн. 2022 г. в 15:22, DrDeLaBill ***@***.***>:

**Comment by DrDeLaBill** [comment]
норм
